# Generated by Django 5.2.8 on 2025-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=500)),
                ('track_name', models.CharField(max_length=500)),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'new_tracks',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=500)),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('download', models.IntegerField(default=0)),
                ('failed_download', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
    ]
