# Generated by Django 5.2.8 on 2025-12-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='relative_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
