# Generated by Django 5.2.8 on 2025-12-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='download',
        ),
        migrations.RemoveField(
            model_name='track',
            name='failed_download',
        ),
        migrations.RemoveField(
            model_name='track',
            name='file_found',
        ),
    ]
