# Generated by Django 5.2.8 on 2025-12-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_remove_track_download_remove_track_failed_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtrack',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newtrack',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
