# Generated by Django 5.2.8 on 2026-01-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_newtrack_downloaded_newtrack_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='skipcount',
            field=models.IntegerField(default=0),
        ),
    ]
