# Generated by Django 5.2.8 on 2026-01-25 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_track_playcount_track_skipcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playcount',
        ),
        migrations.RemoveField(
            model_name='track',
            name='skipcount',
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('playcount', models.IntegerField(default=0)),
                ('skipcount', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to='downloader.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tracks',
                'indexes': [models.Index(fields=['user', 'is_removed'], name='user_tracks_user_id_16d0a7_idx'), models.Index(fields=['user', 'track'], name='user_tracks_user_id_3c4a60_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
