# Generated by Django 5.2.8 on 2026-01-25 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_remove_track_playcount_remove_track_skipcount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrack',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertrack',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertrack',
            name='play_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertrack',
            name='rating',
            field=models.IntegerField(blank=True, help_text='User rating 1-5 stars', null=True),
        ),
        migrations.AddIndex(
            model_name='usertrack',
            index=models.Index(fields=['user', 'favorite'], name='user_tracks_user_id_49124a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrack',
            index=models.Index(fields=['user', 'rating'], name='user_tracks_user_id_cefc79_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrack',
            index=models.Index(fields=['user', 'last_played'], name='user_tracks_user_id_f41e02_idx'),
        ),
    ]
